"""empty message

Revision ID: 1edfb6dbf5ff
Revises: 87f5264147b3
Create Date: 2024-03-03 18:25:23.959410

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1edfb6dbf5ff'
down_revision: Union[str, None] = '87f5264147b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
