"""asd

Revision ID: 6c02a592c536
Revises: 1edfb6dbf5ff
Create Date: 2024-03-03 18:27:44.317469

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c02a592c536'
down_revision: Union[str, None] = '1edfb6dbf5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_login', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
