"""init

Revision ID: 74ddfb15f4d1
Revises: 
Create Date: 2024-03-03 15:58:06.668075

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '74ddfb15f4d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.alpha2'], use_alter=True),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login', 'email', 'phone', name='user_uc'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('added_user_login', sa.String(), nullable=False),
    sa.Column('who_added_user_login', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_user_login'], ['users.login'], ),
    sa.ForeignKeyConstraint(['who_added_user_login'], ['users.login'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('added_user_login', 'who_added_user_login')
    )
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_login'], ['users.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('countries', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('countries', 'alpha2',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('countries', 'alpha3',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('countries', 'region',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'countries', ['alpha2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.alter_column('countries', 'region',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('countries', 'alpha3',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('countries', 'alpha2',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('countries', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_table('tags')
    op.drop_table('posts')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
