"""like table

Revision ID: 87f5264147b3
Revises: b03ea2f58e44
Create Date: 2024-03-03 18:12:49.931706

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '87f5264147b3'
down_revision: Union[str, None] = 'b03ea2f58e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
