
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik_prod:fastapi_traefik_prod@db:5432/fastapi_traefik_prod
      - POSTGRES_USERNAME=prodtest
      - POSTGRES_PASSWORD=prodtest
      - POSTGRES_DATABASE=prodtest
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RANDOM_SECRET=edcdebce761567e6063cb312bfb4cae9d204617dca82c2e9f845fd1d663e691f
      - SERVER_ADRESS=localhost
      - SERVER_PORT=8000

    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=prodtest
      - POSTGRES_PASSWORD=prodtest
      - POSTGRES_DB=prodtest

volumes:
  postgres_data_prod:
